### ISSUE TITLE
How to print from laptop to the shared printer on a network?

### ISSUE THREAD

**Issue by fgroupindonesia** [anastaciocintra/escpos-coffee#73]
supposed i have these output after running the 1st example.

```
========= Printer Names:
Send To OneNote 2010
Microsoft XPS Document Writer
Master PDF Editor 5
Fax
eDocPrinter PDF Pro
\\spc-desktop\58mm Series Printer
========= end.
```

that one for the last **\\spc-desktop\58mm Series Printer**
I unable to connect java for printing by using it.

But if I used a normal casual classical java print API, especially printDialog(); everything works,
including the shared printer. Because it through out the printDialog(); calls....

I wonder if this library escpos-coffee could also solving my current situation as well....

regards,

Gumuruh

**Comment by anastaciocintra** [comment]
I don't know how to help you, but I can review some points about printer name: 

the installed printers can be listed by the command line:

```sh 
java -jar getstart-4.1.0-jar-with-dependencies.jar 
>>>output of my linux machine ...

Usage: java -jar getstart.jar ("printer name")
Printer list to use:
cups_TM_T20_MacBook_Pro_de_Marco
EPSON_TM_T20_MacBook_Pro_de_Marco
TM-T20
```

and when you pass the "printer name" you can send only a substring of the printer name:

```sh 
java -jar getstart-4.1.0-jar-with-dependencies.jar cups_tm
```
instead of 
```sh 
java -jar getstart-4.1.0-jar-with-dependencies.jar  "cups_TM_T20_MacBook_Pro_de_Marco"
```

the code can be found at: https://github.com/anastaciocintra/escpos-coffee-samples/tree/master/usual/getstart

**Comment by fgroupindonesia** [comment]
alright... thanks.
